### PR TITLE
Added config for Basic Spring Security

### PR DESCRIPTION
**Pull request by jnorrick**
- Updated build.gradle to add implementation "org.springframework.boot:spring-boot-starter-security"
- Added Config package and ProjectSecurityConfig Class 
- Added test UserController to test security is working
-Added defaultSecurityChain to ProjectSecurityConfig to determine which routes are authenticated and which are whitelisted (currently the only whitelisted route is "/hello", will update in next iteration once ready to merge)
-Added Spring Security development username and password to application.properties (username = books2borrow, password = books2borrow)
(encoding is currently commented out, will work to re-implement next iteration)

to test that this is working, fetch the branch, run the application, and navigate to http://localhost:8080/
It should request you to enter the username and password to load the page (it currently just navigates to a blank page as we do not have anything at route "/")

Next, to test the whitelisted route, restart the application and navigate to http://localhost:8080/hello
You should be able to see the message "HELLO secure WORLD"

### CODE REVIEW

**Comment by MatthewSpeaks** [comment]
Hi Jessica, 

This looks good. Is there a "create new account" page or some login credentials you can supply us with? Viewed the whitelist page and the login page, but obviously couldn't login without any creds. 

I don't think we can/should merge this pull request until we have a way to login. Currently the authentication this adds blocks the functionality of the Controllers.

**Comment by jnorrick** [comment]
> This looks good. Is there a "create new account" page or some login credentials you can supply us with? Viewed the whitelist page and the login page, but obviously couldn't login without any creds.
> 
> I don't think we can/should merge this pull request until we have a way to login. Currently the authentication this adds blocks the functionality of the Controllers.

The login credentials were listed in the original comment for the pull request! 😅 but it is **books2borrow** for both username and password. 

Once you run the program and navigate to localhost:8080/ a login page should load prompting you to enter the username (books2borrow) and the password (books2borrow). 

The login page should look like this:
image

There is no front end connection currently/react component created.

**Comment by jnorrick** [comment]
Updated UserController for two distinct paths to test w/default security username (books2borrow) and password (books2borrow): 
http://localhost:8080/hello   -> navigate to this, the message should be visible without entering username and password
http://localhost:8080/testing -> should redirect to login, enter username and password, should let you see a message after that
if you try http://localhost:8080/ -> should redirect to login, and then send you to http://localhost:8080/?continue  (which is just a blank page at this point)

**Comment by MatthewSpeaks** [comment]
Hey Jess, It looks like everything is working as intended. Able to login, etc. But it is still blocking requests from Postman with a 401 Unauthorized response when running the branch. 

Are you able to send requests to and from the book API on your end?

**Comment by dalpiad** [comment]
Not sure what I'm doing wrong, I'm using books2borrow as username and password but I get a 403 access denied error:       Access to localhost was denied You don't have authorization to view this page.
HTTP ERROR 403

**Comment by jnorrick** [comment]
Closing this pull request to reopen on a new branch

**Pull request closed without merging**
