### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by ArpithaNagappa**
Check out Navigation and Search bar!

### CODE REVIEW

**Review by dalpiad — APPROVED** [review]
That's awesome! You did a lot of work. I see you incorporated Routes. 

Only comment is we may have to change some things when once logins and user sessions are added.

**Comment by dalpiad** [comment]
Should it being going to the main branch though?

**Comment by dalpiad** [comment]
Should it being going to the main branch though?

**Comment by ArpithaNagappa** [comment]
My bad! not to the main branch (suppose to be frontend -dev).

**Review by jnorrick — COMMENTED** [review]
I pulled the branch down and attempted to run it, I received the following errors:

[vite] Pre-transform error: Failed to resolve import "@mui/material/TextField" from "src/components/SearchBar.jsx". Does the file exist?

[vite] Pre-transform error: Failed to resolve import "react-icons/bs" from "src/components/Navigation.jsx". Does the file exist?

[vite] Pre-transform error: Failed to resolve import "react-icons/bs" from "src/components/Navigation.jsx". Does the file exist? (x2)

so I was not able to get the page to load. Is it working for everyone else?

**Comment by ArpithaNagappa** [comment]
You need to install few things in React. These are the things I installed, please check it out. 
Google font-https://fonts.google.com/selection/embed -- index.html

React -icon----- terminal
https://react-icons.github.io/react-icons/
Include popular icons in your React projects easily with react-icons, which utilizes ES6 imports that allows you to include only the icons that your project is using.
npm install react-icons --save 

https://mui.com/material-ui/----- terminal
Material UI is an open-source React component library that implements Google's Material Design. It's comprehensive and can be used in production out of the box.
npm install @mui/material @emotion/react @emotion/styled
npm install @mui/icons-material

npm install react-router-dom@6

**Pull request merged**
